name: Release Pipeline

on:
  release:
    types: [published]

permissions:
  contents: read
      
jobs:
  build-and-deploy:
    uses: tannenbaum-gmbh/java-platform-deployment/.github/workflows/java-platform-deployment.yml@v0.0.1
    with:
      release_tag_name: ${{ github.event.release.tag_name }}
      release_name: ${{ github.event.release.name }}
      release_html_url: ${{ github.event.release.html_url }}
